# Site settings
title: arainho ~$ ./blog --list
email: arainho.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    $ cat blog | while read post; do echo $post; done
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.arainho.me" # the base hostname & protocol for your site
github_username:  arainho
#twitter_username: arainho_it

comments:
  provider               : "disqus"
  disqus:
    shortname            : arainho

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-78057681-1
