- hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    my-user: "replace-by-username"

  tasks:

    - name: Disable UseRoaming
      lineinfile: 
        dest=/Users/{{ my-user }}/.ssh/config
        line="UseRoaming no"
        state=present
        insertafter=EOF
      when: ansible_os_family == "Darwin"
